<script src="../assets/js/core/popper.min.js"></script>
<script src="../assets/js/core/bootstrap.min.js"></script>
<script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
<script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
<script src="../assets/js/plugins/chartjs.min.js"></script>
<script src="../assets/js/core.js"></script>
<script src="../assets/libs/daterangepicker/moment.min.js"></script>
<script src="../assets/libs/datatable/datatable.js"></script>
<script src="../assets/libs/sweetalert/dist/sweetalert2.all.min.js"></script>
<script src="../assets/libs/daterangepicker/daterangepicker.js"></script>
<script src="../assets/libs/jQueryMask/dist/jquery.mask.js"></script>
<script src="../assets/js/moment.js"></script>
<script src="../assets/libs/daterangepicker/daterangepicker.js"></script>
<script async defer src="https://buttons.github.io/buttons.js"></script>
<script src="../assets/js/material-dashboard.js"></script>